version: "3.9"

services:
  frontend:
    build:
      context: ./front-Docker
      dockerfile: Dockerfile
    container_name: angular-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./front-Docker:/app
      - /app/node_modules
    depends_on:
      - node-app
    networks:
      - app-network

  node-app:
    build:
      context: ./back-Docker
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
